package org.example.zkteco.core;

public enum DeviceCapability {
    IDENTITY_READ,
    DEVICE_TIME_READ, DEVICE_TIME_WRITE,
    USER_READ, USER_WRITE, USER_DELETE,
    ATTENDANCE_READ, ATTENDANCE_REALTIME,
    ACCESS_EVENT_READ, ACCESS_REALTIME,
    CARD_READ, CARD_WRITE,
    FINGERPRINT_TEMPLATE_READ, FINGERPRINT_TEMPLATE_WRITE,
    FACE_TEMPLATE_READ, FACE_TEMPLATE_WRITE,
    PALM_TEMPLATE_READ, PALM_TEMPLATE_WRITE,
    DOOR_UNLOCK, DOOR_LOCK, AUX_OUTPUT_CONTROL,
    DEVICE_REBOOT, DEVICE_ENABLE, DEVICE_DISABLE,
    LOG_CLEAR,
    BIOMETRIC_CAPTURE,
    BIOMETRIC_MATCH,
    RAW_COMMAND
}
