shared.tracing.default.enabled=true
shared.tracing.default.header=web-correlation-id

shared.performance-logging.default.enabled=true
shared.performance-logging.default.min-duration-in-millis=50

shared.logging.excluded-headers=X-Api-Key,Authorization,X-Auth-Token,X-Device-Hub-Key,Cookie

shared.mdc.transaction-id-key=transactionId
shared.mdc.request-id-key=requestId
shared.mdc.external-id-key=externalId
shared.mdc.user-id-key=userId
shared.mdc.roles-key=roles
shared.mdc.tenant-id-key=tenantId
shared.mdc.branch-id-key=branchId
shared.mdc.customer-id-key=customerId

shared.redis.default.expiration-in-minutes=360
