package com.bemo.hr.finance.application;
import com.bemo.hr.finance.domain.*;import com.bemo.hr.finance.infrastructure.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.BigDecimal;import java.time.LocalDate;import java.util.*;
@Service @Transactional(readOnly=true)
public class GeneralLedgerReportService{
 private final JournalEntryRepository entries;private final JournalEntryLineRepository lines;private final AccountRepository accounts;
 public GeneralLedgerReportService(JournalEntryRepository e,JournalEntryLineRepository l,AccountRepository a){entries=e;lines=l;accounts=a;}
 public record Row(String journalId,String entryNumber,LocalDate entryDate,String accountId,String accountCode,String reference,BigDecimal debit,BigDecimal credit,BigDecimal runningBalance){}
 public List<Row> detail(LocalDate from,LocalDate to,String accountId){Map<String,Account> map=new HashMap<>();accounts.findAll().forEach(a->map.put(a.getId(),a));List<Row> out=new ArrayList<>();BigDecimal running=BigDecimal.ZERO;for(JournalEntry e:entries.findByStatusOrderByEntryDateDesc(JournalEntry.Status.POSTED).stream().filter(x->!x.getEntryDate().isBefore(from)&&!x.getEntryDate().isAfter(to)).sorted(Comparator.comparing(JournalEntry::getEntryDate).thenComparing(JournalEntry::getEntryNumber)).toList()){for(JournalEntryLine l:lines.findByJournalEntryId(e.getId())){if(accountId!=null&&!accountId.equals(l.getAccountId()))continue;running=running.add(l.getDebit()).subtract(l.getCredit());Account a=map.get(l.getAccountId());out.add(new Row(e.getId(),e.getEntryNumber(),e.getEntryDate(),l.getAccountId(),a==null?l.getAccountId():a.getCode(),e.getReference(),l.getDebit(),l.getCredit(),running));}}return out;}
 public byte[] exportCsv(LocalDate from,LocalDate to,String accountId){StringBuilder b=new StringBuilder("entryNumber,entryDate,accountCode,reference,debit,credit,runningBalance\n");detail(from,to,accountId).forEach(r->b.append(r.entryNumber()).append(',').append(r.entryDate()).append(',').append(r.accountCode()).append(',').append(r.reference()==null?"":r.reference()).append(',').append(r.debit()).append(',').append(r.credit()).append(',').append(r.runningBalance()).append('\n'));return b.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8);}
}
