export type BusinessReportModule =
  | 'dashboard'
  | 'workforce'
  | 'attendance'
  | 'payroll'
  | 'finance'
  | 'procurement'
  | 'sales'
  | 'inventory'
  | 'manufacturing'
  | 'governance'
;

export interface BusinessReportDefinition {
  id: string;
  number: string;
  module: BusinessReportModule;
  titleEn: string;
  titleAr: string;
  sourceRoutes: readonly string[];
  workspaceRoute: string;
  objective: string;
  entities: readonly string[];
  filters: readonly string[];
  metrics: readonly string[];
  trigger: string;
  exportFormats: readonly string[];
}

export const BUSINESS_REPORT_MODULES: readonly BusinessReportModule[] = [
  'dashboard', 'workforce', 'attendance', 'payroll', 'finance', 'procurement', 'sales', 'inventory', 'manufacturing', 'governance'
];

export const BUSINESS_REPORT_CATALOG: readonly BusinessReportDefinition[] = [
  {
    id: 'report-1-1',
    number: '1.1',
    module: 'dashboard',
    titleEn: 'Executive Operational & Financial Snapshot',
    titleAr: 'ملخص الأداء التنفيذي والسيولة',
    sourceRoutes: ['/dashboard'],
    workspaceRoute: '/dashboard',
    objective: 'Provides C-level and operations directors with immediate visibility into liquidity, daily workforce attendance, outstanding receivables/payables, and operational bottlenecks',
    entities: ['JournalEntryLine', 'CustomerInvoice', 'SupplierInvoice', 'WorkerSettlement', 'BiometricDevice'],
    filters: [
      'Date Range (Today, MTD, QTD, YTD)',
      'Company / Branch / Operational Unit',
      'Reporting Currency',
    ],
    metrics: [
      'Cash & Bank Liquidity: Total available bank balances vs. upcoming 7-day payment commitments',
      'Workforce Deployment: Active workers on-site vs. planned headcount, attendance rate, anomaly rate',
      'Working Capital: Total Accounts Receivable (AR) vs. Accounts Payable (AP), Overdue > 30 Days',
      'Operating Margin: Net revenue, Cost of Goods Sold (COGS), Gross Profit ($ and %)',
    ],
    trigger: 'Alerts management to upcoming cash crunches, abnormal labor shortages, or production variances',
    exportFormats: ['PDF (Board Brief)', 'Excel (Financial Breakdown)'],
  },
  {
    id: 'report-2-1',
    number: '2.1',
    module: 'workforce',
    titleEn: 'Contractor Period Settlement Statement',
    titleAr: 'كشف تصفية مستحقات مقاولي الأنفار',
    sourceRoutes: ['/workforce/settlement-periods'],
    workspaceRoute: '/workforce/settlement-periods',
    objective: 'Reconciles gross worker hours and agreed contractor billing rates against cash advances, attendance penalties, and disputes to compute the final net payable to each labor contractor',
    entities: ['ContractorSettlement', 'ContractorSettlementLine', 'WorkforceAdvanceLedgerEntry', 'LaborDispatch'],
    filters: [
      'Settlement Period (Weekly, Bi-Weekly, Monthly)',
      'Contractor / Labor Agency',
      'Project Site / Branch',
      'Status (DRAFT, CALCULATED, APPROVED, SETTLED)',
    ],
    metrics: [
      'Contractor Name & Tax/CR ID',
      'Dispatched Worker Count & Total Man-Hours / Days',
      'Agreed Hourly / Daily Rate per Role',
      'Gross Labor Cost ($)',
      'Deductions: Worker Cash Advances Settled, Absence/Dispute Penalties, Equipment Holdbacks',
      'Withholding Tax (WHT) Deductions (if applicable)',
      'Net Settlement Amount Payable ($)',
    ],
    trigger: 'Authorizes treasury release and blocks payment if unrecovered contractor advances exist',
    exportFormats: ['Excel (Detailed Line Items)', 'PDF (Official Payment Voucher)'],
  },
  {
    id: 'report-2-2',
    number: '2.2',
    module: 'workforce',
    titleEn: 'Daily Labor Dispatch & Dispute Audit',
    titleAr: 'سجل تشغيل ومنازعات العمالة اليومية',
    sourceRoutes: ['/workforce/dispatch-disputes', '/workforce/labor-requests'],
    workspaceRoute: '/workforce/labor-requests',
    objective: 'Audits daily site staffing by comparing requested labor against dispatched and verified attendance, flagging all billing disputes before settlements are generated',
    entities: ['LaborRequest', 'LaborRequestItem', 'LaborDispatch', 'WorkforceDispute'],
    filters: [
      'Shift Date / Project Site',
      'Requesting Department / Supervisor',
      'Contractor Agency',
      'Dispute Status (OPEN, RESOLVED, REJECTED)',
    ],
    metrics: [
      'Labor Request ID, Shift Date, Requested Skill Category, Requested Count',
      'Contractor Dispatched Count, Verified Check-In Count, Variance (Shortage/Surplus)',
      'Disputed Worker ID / Name, Disputed Hours',
      'Dispute Reason (Late Arrival, Missing Safety Gear, Unqualified Worker, Unauthorized Departure)',
      'Financial Adjustment Amount ($), Approving Field Supervisor',
    ],
    trigger: 'Applies contractual SLA penalties against labor contractors and provides an immutable audit trail for contested hours',
    exportFormats: ['Excel', 'CSV'],
  },
  {
    id: 'report-2-3',
    number: '2.3',
    module: 'workforce',
    titleEn: 'Workforce Advance Ledger & Recovery Tracker',
    titleAr: 'كشف حساب سلف العمالة والاستقطاعات',
    sourceRoutes: ['/workforce/advances'],
    workspaceRoute: '/workforce/advances',
    objective: 'Tracks active cash advances granted to daily laborers and subcontractors against agreed installment recovery schedules to mitigate default risk',
    entities: ['WorkforceAdvance', 'WorkforceAdvanceInstallment', 'WorkforceAdvanceLedgerEntry'],
    filters: [
      'Worker Code / Name / National ID',
      'Contractor Agency',
      'Advance Policy / Loan Type',
      'Recovery Status (ACTIVE, PARTIALLY_RECOVERED, SETTLED, DEFAULTED)',
    ],
    metrics: [
      'Worker Code, Full Name, National ID, Mobile Wallet Number',
      'Advance Disbursement Date, Principal Advance Amount ($), Approved By',
      'Installment Amount per Pay Cycle, Total Recovered to Date ($), Remaining Principal ($)',
      'Attendance Health Indicator (Active Days Worked in Current Period)',
      'Default Risk Flag (Active balance with 0 attendance in >14 days)',
    ],
    trigger: 'Automatically blocks new cash advance requests if outstanding balance exceeds policy limits or worker attendance drops',
    exportFormats: ['Excel', 'PDF Statement'],
  },
  {
    id: 'report-3-1',
    number: '3.1',
    module: 'attendance',
    titleEn: 'Daily Attendance Anomaly & Exception Review',
    titleAr: 'تقرير شذوذ وسجلات الحضور والانصراف',
    sourceRoutes: ['/reporting/report-review', '/reporting'],
    workspaceRoute: '/reports',
    objective: 'Identifies missing punches, grace period violations, unexcused absences, and unauthorized overtime before attendance is locked for payroll',
    entities: ['DailyAttendanceResult', 'DayAnomaly', 'AttendanceException', 'AttendancePolicy'],
    filters: [
      'Date Range / Pay Period',
      'Branch / Facility / Gate',
      'Department / Employee Category (Salaried, Shift, Daily Labor)',
      'Anomaly Type (MISSING_IN, MISSING_OUT, LATE_ARRIVAL, EARLY_DEPARTURE, UNAUTHORIZED_OT)',
    ],
    metrics: [
      'Employee Code, Name, Department, Assigned Schedule Rule',
      'First Check-In, Last Check-Out, Total Clocked Hours, Expected Shift Hours',
      'Calculated Lateness (Minutes), Early Departure (Minutes), Unpaid Absence (Days)',
      'Penalty Deduction (Hours/Days) or Approved Overtime Hours',
      'Resolution Decision (PENDING_SUPERVISOR, APPROVED_JUSTIFIED, DEDUCTION_ENFORCED)',
    ],
    trigger: 'Enables HR to resolve all attendance exceptions before locking the period for automated salary calculations',
    exportFormats: ['Excel', 'CSV'],
  },
  {
    id: 'report-3-2',
    number: '3.2',
    module: 'attendance',
    titleEn: 'Biometric Terminal Connectivity & Ingest Health Log',
    titleAr: 'سجل جاهزية واتصال أجهزة البصمة',
    sourceRoutes: ['/device-integrations'],
    workspaceRoute: '/imports/device-integrations',
    objective: 'Provides IT and facility managers with real-time diagnostics on biometric clocking terminals to prevent lost attendance records',
    entities: ['BiometricDevice', 'BiometricSource', 'PunchImportEvidence', 'ImportRowError'],
    filters: [
      'Vendor (ZKTECO, HIKVISION, DAHUA, SUPREMA, VIRDI, ANVIZ)',
      'Branch / Location / Gate',
      'Protocol (ADMS HTTP Push, ISAPI, Standalone TCP/IP, BioStar API)',
      'Status (ONLINE, OFFLINE, DEGRADED)',
    ],
    metrics: [
      'Device Name, IP Address, Serial Number, Firmware Version',
      'Communication Status, Last Successful Heartbeat, Last Punch Sync Time',
      'Pending Punch Buffer Count, Ingestion Error Count (Unrecognized ID, Corrupted Format)',
    ],
    trigger: 'Generates instant alerts when a terminal goes offline or its local storage buffer approaches maximum capacity',
    exportFormats: ['CSV', 'System Health Log'],
  },
  {
    id: 'report-4-1',
    number: '4.1',
    module: 'payroll',
    titleEn: 'Master Payroll Summary & Bank Disbursement Sheet',
    titleAr: 'كشف الرواتب المعتمد وحوالات البنوك',
    sourceRoutes: ['/payroll'],
    workspaceRoute: '/payroll',
    objective: 'Detailed financial schedule of employee earnings, allowances, statutory deductions, tax withholdings, and net payable amounts',
    entities: ['PayrollRunHeader', 'PayrollRunLine', 'SalaryPayment', 'PayrollComponent'],
    filters: [
      'Pay Period / Year',
      'Branch / Cost Center / Department',
      'Payment Method (Bank Transfer / ACH, Cash, Mobile Wallet, InstaPay)',
    ],
    metrics: [
      'Employee Code, Name, Title, Bank IBAN / Mobile Wallet ID',
      'Basic Salary, Fixed Allowances (Housing, Transportation, Meals)',
      'Variable Compensation (Overtime, Performance Bonus, Sales Commissions)',
      'Deductions: Social Insurance (Employee Share), Income Tax Withholding, Loan/Advance Installments, Absence Penalties',
      'Employer Statutory Contributions (Social Insurance Employer Share, Medical Fund)',
      'Net Salary Payable ($), Bank Batch Allocation Reference',
    ],
    trigger: 'Exports bank-ready disbursement files (WPS SIF / ACH) and triggers automated posting of the payroll journal entry',
    exportFormats: ['Excel (Master Payroll Register)', 'Bank SIF / CSV', 'PDF Payslips'],
  },
  {
    id: 'report-4-2',
    number: '4.2',
    module: 'payroll',
    titleEn: 'Payroll Variance & Retroactive Adjustment Audit',
    titleAr: 'تقرير فروقات الرواتب والتسويات الراجعة',
    sourceRoutes: ['/payroll/retro', '/payroll/gl-postings'],
    workspaceRoute: '/payroll',
    objective: 'Audits month-over-month payroll discrepancies and details retroactive salary corrections to ensure financial transparency',
    entities: ['PayrollRetroAdjustment', 'PayrollInputSnapshot', 'SalaryPaymentExplanation'],
    filters: [
      'Current Pay Period vs. Comparison Period',
      'Variance Threshold (> ±10% or > $500)',
      'Department / Cost Center',
    ],
    metrics: [
      'Employee Name, Prior Period Net Salary, Current Period Net Salary, Net Variance ($ and %)',
      'Categorized Variance Drivers: Base Pay Raise, Overtime Spike, Unpaid Leave, Retroactive Deduction/Addition',
      'System Explanation Note, Approving HR Manager',
    ],
    trigger: 'Mandatory review item for internal controllers before approving the monthly payroll batch',
    exportFormats: ['Excel', 'PDF'],
  },
  {
    id: 'report-5-1',
    number: '5.1',
    module: 'finance',
    titleEn: 'General Ledger & Trial Balance Report',
    titleAr: 'ميزان المراجعة ودفتر الأستاذ العام',
    sourceRoutes: ['/finance/accounts', '/finance/journal-entries'],
    workspaceRoute: '/finance/journal-entries',
    objective: 'Validates the accounting equation across all levels of the Chart of Accounts, serving as the basis for financial statement generation',
    entities: ['Account', 'JournalEntry', 'JournalEntryLine', 'FiscalPeriod'],
    filters: [
      'Fiscal Year / Period',
      'Account Range / Account Category (Assets, Liabilities, Equity, Revenues, Expenses)',
      'Cost Center / Branch / Project Dimension',
      'Inclusion of Draft / Unposted Journals',
    ],
    metrics: [
      'Account Code, Account Name (Bilingual Arabic / English), Account Type',
      'Opening Balance (Debit / Credit)',
      'Period Activity: Total Debits, Total Credits, Net Period Movement',
      'Ending Balance (Debit / Credit)',
      'Interactive Drill-Down to Source Journal Entries and Subledger Documents',
    ],
    trigger: 'Identifies debit/credit imbalances and generates balance sheets and income statements',
    exportFormats: ['Excel (Formatted Matrix)', 'PDF (Official Financial Report)'],
  },
  {
    id: 'report-5-2',
    number: '5.2',
    module: 'finance',
    titleEn: 'Bank Reconciliation & Difference Schedule',
    titleAr: 'مذكرة تسوية البنك والفروقات',
    sourceRoutes: ['/finance/banks'],
    workspaceRoute: '/finance/banks',
    objective: 'Reconciles external bank statement transactions against internal treasury ledgers, highlighting unpresented checks, deposits in transit, and bank fees',
    entities: ['BankStatement', 'BankStatementLine', 'BankReconciliationMatch', 'BankDifferencePosting'],
    filters: [
      'Bank Account / Currency',
      'Statement Date Range',
      'Reconciliation Status (MATCHED, UNMATCHED, AUTO_DIFFERENCE_POSTED)',
    ],
    metrics: [
      'Statement Date, Value Date, Bank Transaction Reference, Description, Bank Debit/Credit',
      'Internal Book Match: Journal Entry ID, Payment Batch Ref, Book Date, Book Amount',
      'Unmatched Exception Classification (Outstanding Check, Deposit in Transit, Bank Service Fee, Exchange Rate Loss/Gain)',
      'Reconciled Bank Statement Balance vs. Reconciled General Ledger Cash Balance (Variance = 0.00)',
    ],
    trigger: 'Automatically drafts bank fee adjustment journals and flags stale uncashed checks',
    exportFormats: ['Excel', 'PDF'],
  },
  {
    id: 'report-5-3',
    number: '5.3',
    module: 'finance',
    titleEn: 'Budget vs. Actual & Encumbrance Utilization',
    titleAr: 'تقرير الموازنة مقابل الفعلي والارتباطات',
    sourceRoutes: ['/finance/budgets'],
    workspaceRoute: '/finance/budgets',
    objective: 'Prevents departmental overspending by comparing approved budgets against posted actual expenses and committed purchase encumbrances',
    entities: ['Budget', 'BudgetVersion', 'Encumbrance', 'JournalEntryLine'],
    filters: [
      'Fiscal Year / Budget Version',
      'Department / Cost Center / Project',
      'Expense Account Group',
    ],
    metrics: [
      'Budget Line Description, Account Code, Department',
      'Original Approved Budget, Approved Transfers/Revisions, Total Revised Budget ($)',
      'Actual Posted Expenses (YTD / MTD)',
      'Active Encumbrances (Committed Purchase Orders not yet invoiced)',
      'Total Committed Funds (Actuals + Encumbrances), Remaining Available Budget ($), % Utilized',
    ],
    trigger: 'Automatically blocks purchase requisitions when remaining budget reaches zero',
    exportFormats: ['Excel', 'PDF'],
  },
  {
    id: 'report-5-4',
    number: '5.4',
    module: 'finance',
    titleEn: 'Period Close Control Workbench',
    titleAr: 'تقرير تدقيق إقفال الفترة المالية',
    sourceRoutes: ['/fiscal-periods'],
    workspaceRoute: '/fiscal-periods',
    objective: 'Executes pre-closing controls across subledgers (AP, AR, Inventory, Payroll, Manufacturing) before locking fiscal periods',
    entities: ['PeriodCloseExecutionRecord', 'FiscalPeriodGuard', 'SubledgerReconciliationReport'],
    filters: [
      'Target Fiscal Period',
      'Subledger Module',
    ],
    metrics: [
      'Subledger Name (Accounts Payable, Accounts Receivable, Inventory, Payroll, Treasury)',
      'Subledger Balance vs. General Ledger Control Account Balance',
      'Discrepancy Amount (Variance)',
      'Blocker Count (Draft journals, unposted goods receipts, unapproved invoices)',
      'Readiness Verdict (READY_TO_CLOSE, BLOCKED_BY_EXCEPTIONS)',
    ],
    trigger: 'Enforces strict audit governance before advancing fiscal period status to CLOSED',
    exportFormats: ['PDF (Close Audit Certificate)', 'Excel'],
  },
  {
    id: 'report-6-1',
    number: '6.1',
    module: 'procurement',
    titleEn: 'Three-Way Match & Price Variance Audit',
    titleAr: 'تقرير المطابقة الثلاثية وفروقات الأسعار',
    sourceRoutes: ['/trade/procurement'],
    workspaceRoute: '/trade/procurement',
    objective: 'Compares Purchase Order (PO), Goods Receipt Note (GRN), and Supplier Invoice to prevent overbilling, duplicate payments, and unreceived goods payments',
    entities: ['ProcurementThreeWayMatch', 'PurchaseOrder', 'GoodsReceipt', 'SupplierInvoice'],
    filters: [
      'Supplier / Vendor',
      'Date Range / PO Number',
      'Match Status (MATCHED, QTY_VARIANCE, PRICE_VARIANCE, TOLERANCE_EXCEEDED)',
    ],
    metrics: [
      'PO Number, Item Code, Ordered Qty, Unit PO Price ($)',
      'GRN Number, Warehouse, Received Qty',
      'Supplier Invoice Number, Billed Qty, Invoiced Unit Price, Invoiced Total ($)',
      'Quantity Variance (Billed vs. Received), Price Variance (Billed vs. PO)',
      'Tolerance Status (Within 2% Policy Tolerance vs. Exceeded — Requires Approval Override)',
    ],
    trigger: 'Automatically places high-variance supplier invoices on payment hold',
    exportFormats: ['Excel', 'PDF'],
  },
  {
    id: 'report-6-2',
    number: '6.2',
    module: 'procurement',
    titleEn: 'GR/IR Clearing Account Ledger',
    titleAr: 'تقرير تسوية حساب البضاعة المستلمة غير المفوترة',
    sourceRoutes: ['/trade/procurement'],
    workspaceRoute: '/trade/procurement',
    objective: 'Tracks the Goods Received / Invoice Received (GR/IR) clearing account to identify received goods pending invoice or invoiced goods pending delivery',
    entities: ['GrirReconciliationRecord', 'GoodsReceiptLine', 'SupplierInvoice'],
    filters: [
      'Aging Bucket (<30, 31-60, 61-90, >90 Days)',
      'Supplier / Vendor',
      'Receiving Warehouse',
    ],
    metrics: [
      'GRN Number, Receipt Date, Item Code, Description, Quantity Received',
      'Receipt Valuation Amount ($) [Credit to GR/IR]',
      'Matched Supplier Invoice Ref, Invoiced Amount ($) [Debit to GR/IR]',
      'Open Uninvoiced Balance ($), Days Outstanding',
    ],
    trigger: 'Alerts procurement to demand missing invoices from suppliers before month-end close',
    exportFormats: ['Excel', 'CSV'],
  },
  {
    id: 'report-6-3',
    number: '6.3',
    module: 'procurement',
    titleEn: 'Vendor Payment Proposal & Cash Allocation',
    titleAr: 'اقتراح وجدولة سداد الموردين والخصومات',
    sourceRoutes: ['/trade/procurement'],
    workspaceRoute: '/trade/procurement',
    objective: 'Optimizes working capital by scheduling supplier payments based on net due dates, early payment cash discounts, and vendor risk profiles',
    entities: ['VendorPaymentProposal', 'VendorPaymentProposalAllocation', 'SupplierInvoice', 'PartnerRiskScoreSnapshot'],
    filters: [
      'Proposed Payment Date',
      'Payment Run Batch ID',
      'Currency / Bank Account',
      'Supplier Risk Tier (LOW, MEDIUM, HIGH)',
    ],
    metrics: [
      'Supplier Name, Risk Score, Bank IBAN',
      'Invoice Number, Invoice Date, Due Date, Invoice Amount ($)',
      'Early Payment Discount Available ($), Late Payment Penalty ($)',
      'Allocated Payment Amount ($), Disbursing Bank Account',
    ],
    trigger: 'Batch approval for treasury release via direct bank file generation',
    exportFormats: ['Excel', 'Bank Payment File (ACH/SIF)'],
  },
  {
    id: 'report-7-1',
    number: '7.1',
    module: 'sales',
    titleEn: 'Accounts Receivable (AR) Aging & Collection Schedule',
    titleAr: 'أعمار الديون والتحصيل',
    sourceRoutes: ['/trade/sales'],
    workspaceRoute: '/trade/sales',
    objective: 'Minimizes Days Sales Outstanding (DSO) and prevents bad debts by monitoring overdue customer invoices across standardized aging intervals',
    entities: ['CustomerInvoice', 'CustomerCreditProfile', 'CustomerReceipt', 'CollectionTask'],
    filters: [
      'Sales Rep / Branch',
      'Customer Category / Tier',
      'Aging Interval (Current, 1–30 Days, 31–60 Days, 61–90 Days, 90+ Days Overdue)',
    ],
    metrics: [
      'Customer Name, Approved Credit Limit ($), Current Limit Utilization (%)',
      'Total Outstanding Balance ($), Current (Not Overdue) Balance ($)',
      'Aging Breakdown: 1–30 Days, 31–60 Days, 61–90 Days, 90+ Days Overdue',
      'Last Payment Date & Amount ($), Assigned Collection Agent, Open Collection Task Status',
    ],
    trigger: 'Automatically suspends credit and blocks new Sales Orders for customers exceeding credit limits or with balances >60 days overdue',
    exportFormats: ['Excel', 'PDF Customer Account Statement'],
  },
  {
    id: 'report-7-2',
    number: '7.2',
    module: 'sales',
    titleEn: 'Sales Profitability & Pricing Snapshot Analysis',
    titleAr: 'تحليل ربحية المبيعات وهامش الربح',
    sourceRoutes: ['/trade/sales'],
    workspaceRoute: '/trade/sales',
    objective: 'Evaluates gross margins across products, customer accounts, and sales teams by analyzing net selling prices against FIFO/standard inventory costs',
    entities: ['SalesOrder', 'SalesOrderLine', 'SalesPricingSnapshot', 'InventoryCostLayer'],
    filters: [
      'Period (Month, Quarter, Year)',
      'Product Category / Brand',
      'Customer / Customer Group',
      'Sales Representative',
    ],
    metrics: [
      'Item Code, Item Name, Quantity Sold, Unit List Price ($)',
      'Applied Discount (%), Net Unit Price ($), Total Revenue ($)',
      'Unit Inventory Cost (FIFO/WAC), Total COGS ($)',
      'Gross Profit ($), Gross Margin (%)',
    ],
    trigger: 'Flags low-margin transactions and restricts discount overrides that breach minimum profitability thresholds',
    exportFormats: ['Excel', 'PDF'],
  },
  {
    id: 'report-8-1',
    number: '8.1',
    module: 'inventory',
    titleEn: 'Inventory Valuation & Stock Movement Audit',
    titleAr: 'تقييم المخزون وحركة الأصناف',
    sourceRoutes: ['/operations'],
    workspaceRoute: '/operations',
    objective: 'Comprehensive stock ledger reporting balances and valuations under FIFO / Weighted Average Costing (WAC) for financial reporting and inventory control',
    entities: ['InventoryItem', 'StockMovement', 'InventoryCostLayer', 'StockValuationRecord'],
    filters: [
      'Warehouse / Bin Location',
      'Item Category / Valuation Policy',
      'Date Range',
    ],
    metrics: [
      'Item Code, Description, Unit of Measure (UoM), Primary Warehouse/Bin',
      'Opening Stock Qty & Value ($)',
      'Inflows: Purchase Receipts, Production Inbound, Transfers In, Positive Adjustments (Qty & Value)',
      'Outflows: Sales Deliveries, Production Issues, Transfers Out, Negative Adjustments (Qty & Value)',
      'Closing Stock on Hand, Reserved Qty, Available Qty, Unit Cost ($), Total Ending Valuation ($)',
    ],
    trigger: 'Reconciles physical inventory balances with the General Ledger Inventory Asset control account',
    exportFormats: ['Excel', 'PDF'],
  },
  {
    id: 'report-8-2',
    number: '8.2',
    module: 'inventory',
    titleEn: 'Lot & Serial Traceability & Expiry Report',
    titleAr: 'تتبع أرقام التشغيلات وتواريخ الصلاحية',
    sourceRoutes: ['/operations'],
    workspaceRoute: '/operations',
    objective: 'Provides end-to-end pedigree tracking of lots and serial numbers for quality recalls, warranty tracking, and perishable expiry management',
    entities: ['ItemLotSerial', 'StockMovement', 'SupplierInvoice', 'SalesDeliveryHeader'],
    filters: [
      'Lot / Serial Number / Item Code',
      'Expiry Date Window (Expiring in 30, 60, 90 Days)',
      'Status (RELEASED, QUARANTINE, EXPIRED, CONSUMED)',
    ],
    metrics: [
      'Item Code, Description, Lot / Serial Number, Current Status',
      'Manufacturing Date, Expiration Date, Remaining Shelf Life (Days)',
      'Originating PO #, Supplier Name, Inbound GRN Date',
      'Quantity on Hand, Current Warehouse / Bin Location',
      'Outbound Sales Delivery / Production Order Reference (if shipped/consumed)',
    ],
    trigger: 'Automatically moves near-expiry lots to QUARANTINE status to prevent dispatch to customers',
    exportFormats: ['Excel', 'CSV'],
  },
  {
    id: 'report-9-1',
    number: '9.1',
    module: 'manufacturing',
    titleEn: 'Production Order Costing & Variance Analysis',
    titleAr: 'تكلفة الإنتاج تحت التشغيل وانحرافات الأوامر',
    sourceRoutes: ['/manufacturing/production'],
    workspaceRoute: '/manufacturing/production',
    objective: 'Compares planned standard BOM component costs and direct labor against actual material issues and clocked worker hours to isolate manufacturing inefficiencies',
    entities: ['ProductionOrder', 'BomSnapshot', 'MaterialIssueLine', 'WipPostingRecord', 'ProductionVarianceClose'],
    filters: [
      'Production Order ID / Finished Product',
      'Production Line / Work Center',
      'Status (RELEASED, IN_PROGRESS, COMPLETED, CLOSED)',
    ],
    metrics: [
      'Production Order #, Finished Item Code, Target Qty, Completed Qty',
      'Planned Material Cost (BOM Snapshot) vs. Actual Material Issued Cost ($)',
      'Planned Direct Labor Hours vs. Actual Clocked Workforce Hours',
      'Total Standard Production Cost ($) vs. Total Actual WIP Incurred ($)',
      'Material Usage Variance ($), Labor Efficiency Variance ($), Net Variance ($)',
    ],
    trigger: 'Posts favorable/unfavorable production variances to P&L accounts during order closeout',
    exportFormats: ['Excel', 'PDF'],
  },
  {
    id: 'report-9-2',
    number: '9.2',
    module: 'manufacturing',
    titleEn: 'Quality Inspection & Stock Disposition Log',
    titleAr: 'سجل فحص الجودة وتصريف المخزون',
    sourceRoutes: ['/manufacturing/quality'],
    workspaceRoute: '/manufacturing/quality',
    objective: 'Tracks raw material receiving and finished goods quality inspection results, isolating supplier defects and scrap costs',
    entities: ['QualityPlanHeader', 'QualityInspection', 'QualityStockDisposition'],
    filters: [
      'Inspection Type (Inbound Raw Material, In-Process, Finished Goods)',
      'Supplier / Vendor',
      'Inspector / Date Range',
      'Disposition (ACCEPTED, REJECTED_RETURNED, SCRAPPED, REWORK)',
    ],
    metrics: [
      'Inspection Ticket #, Item Code, Lot Number, Inspected Sample Size',
      'Quality Parameters Checked (Dimensions, Chemical/Physical Test, Visual Inspection)',
      'Inspection Verdict (PASS, FAIL, CONCESSION)',
      'Stock Disposition Action Taken, Total Scrapped / Returned Quantity',
      'Defect Rate (%) and Cumulative Supplier Quality Rating',
    ],
    trigger: 'Updates supplier risk score and automatically blocks rejected lots from warehouse inventory',
    exportFormats: ['Excel', 'PDF'],
  },
  {
    id: 'report-10-1',
    number: '10.1',
    module: 'governance',
    titleEn: 'Segregation of Duties (SoD) & Sensitive Activity Log',
    titleAr: 'تدقيق الصلاحيات والعمليات الحساسة',
    sourceRoutes: ['/audit-logs', '/approvals'],
    workspaceRoute: '/audit-logs',
    objective: 'Flags compliance and security policy violations, specifically where a single user initiated and approved sensitive financial or master data changes',
    entities: ['AuditLog', 'ApprovalDecision', 'AppUser', 'Role'],
    filters: [
      'Event Category (SECURITY, FINANCIAL, MASTER_DATA, SYSTEM_SETTING)',
      'User ID / Username / Role',
      'Date & Time Window',
    ],
    metrics: [
      'Timestamp, Client IP Address, Username, Assigned Role Code',
      'Action Executed (e.g., APPROVE_SUPPLIER_INVOICE, MODIFY_BANK_ACCOUNT, MANUAL_ATTENDANCE_OVERRIDE)',
      'Entity Name, Target Record ID, Pre-Change Value, Post-Change Value',
      'SoD Conflict Flag (e.g., User created PO and also approved Goods Receipt)',
    ],
    trigger: 'Dispatches real-time compliance alerts to the System Administrator for investigation',
    exportFormats: ['CSV', 'Audit PDF'],
  },
];
