package com.bemo.hr.shared.security;

public enum RoleCode {
    SUPER_ADMIN,
    ADMIN,
    HR_MANAGER,
    HR_REVIEWER,
    VIEWER,
    FINANCE_MANAGER,
    ACCOUNTANT,
    TREASURY_USER,
    PROCUREMENT_MANAGER,
    PROCUREMENT_USER,
    SALES_MANAGER,
    INVENTORY_MANAGER,
    MANUFACTURING_MANAGER,
    QUALITY_MANAGER,
    PAYROLL_MANAGER,
    WORKFORCE_MANAGER,
    WORKFORCE_REVIEWER,
    WORKFORCE_FINANCE,
    PROJECT_MANAGER,
    GENERAL_MANAGER,
    AUDITOR
}
