package com.bemo.hr.product.subscription;
import com.bemo.hr.audit.application.AuditService;import com.bemo.hr.shared.domain.BusinessRuleException;import com.bemo.hr.shared.security.*;import org.junit.jupiter.api.*;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.*;import org.mockito.junit.jupiter.MockitoExtension;import org.springframework.security.access.prepost.PreAuthorize;import tools.jackson.databind.ObjectMapper;import java.time.Instant;import java.util.*;import static org.assertj.core.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class)class SubscriptionServiceTests{@Mock SubscriptionPlanRepository planRepository;@Mock TenantSubscriptionRepository subscriptionRepository;@Mock SubscriptionChangeRepository changeRepository;@Mock TenantApplicationRepository tenantRepository;@Mock EntitlementManagementService entitlementService;@Mock AppUserRepository userRepository;@Mock AuditService auditService;SubscriptionService service;TenantApplication tenant;EntitlementCatalog catalog=new EntitlementCatalog();
@BeforeEach void setup(){tenant=new TenantApplication("sub","Subscription");TenantContext.set(tenant.getId());service=new SubscriptionService(planRepository,subscriptionRepository,changeRepository,tenantRepository,entitlementService,catalog,userRepository,new ObjectMapper(),auditService);lenient().when(tenantRepository.findByIdForUpdate(tenant.getId())).thenReturn(Optional.of(tenant));lenient().when(changeRepository.findByOperationId(anyString())).thenReturn(Optional.empty());lenient().when(subscriptionRepository.findCurrentForUpdate()).thenReturn(Optional.empty());lenient().when(subscriptionRepository.save(any())).thenAnswer(i->i.getArgument(0));}
@AfterEach void clear(){TenantContext.clear();}
@Test void planChangeSynchronizesEntitlementsAndCreatesImmutableEvidence(){var plan=new SubscriptionPlan("STARTER","البداية","Starter","[\"employeeAttendance.enabled\",\"biometric.fileImport.enabled\"]","{\"users\":10}");when(planRepository.findById("STARTER")).thenReturn(Optional.of(plan));var request=new SubscriptionApi.ChangeRequest("starter","ACTIVE",Instant.now().toEpochMilli(),0,0,"New contract","op-1",0);var result=service.change(request,"admin");assertThat(result.replayed()).isFalse();assertThat(result.subscription().planCode()).isEqualTo("STARTER");verify(entitlementService).applyPlan(eq(tenant.getId()),eq(Set.of("employeeAttendance.enabled","biometric.fileImport.enabled")),contains("New contract"),eq("admin"));verify(changeRepository).save(argThat(c->c.getOperationId().equals("op-1")&&c.getReason().equals("New contract")));verify(auditService).record(eq("CHANGE"),eq("TENANT_SUBSCRIPTION"),eq(tenant.getId()),eq("admin"),contains("STARTER"),isNull());}
@Test void operationReplayDoesNotMutateEntitlements(){var existing=new TenantSubscription("STARTER","ACTIVE",Instant.now(),null,null,"op-1","admin");var change=new SubscriptionChange(null,"STARTER",null,"ACTIVE","reason","op-1","admin");when(changeRepository.findByOperationId("op-1")).thenReturn(Optional.of(change));when(subscriptionRepository.findFirstBy()).thenReturn(Optional.of(existing));var request=new SubscriptionApi.ChangeRequest("STARTER","ACTIVE",Instant.now().toEpochMilli(),0,0,"reason","op-1",0);assertThat(service.change(request,"admin").replayed()).isTrue();verifyNoInteractions(entitlementService);verify(subscriptionRepository,never()).save(any());}
@Test void invalidDatesAndInactivePlansAreRejected(){var inactive=new SubscriptionPlan("OLD","قديم","Old","[\"finance.enabled\"]","{}");inactive.update("قديم","Old","[\"finance.enabled\"]","{}",false);when(planRepository.findById("OLD")).thenReturn(Optional.of(inactive));var request=new SubscriptionApi.ChangeRequest("OLD","ACTIVE",1000,0,0,"reason","op",0);assertThatThrownBy(()->service.change(request,"admin")).isInstanceOfSatisfying(BusinessRuleException.class,e->assertThat(e.getCode()).isEqualTo("SUBSCRIPTION_PLAN_NOT_FOUND"));}
@Test void cancellationDisablesCommercialFeaturesWithoutDeletingBusinessData(){var plan=new SubscriptionPlan("STARTER","البداية","Starter","[\"finance.enabled\"]","{}");when(planRepository.findById("STARTER")).thenReturn(Optional.of(plan));var request=new SubscriptionApi.ChangeRequest("STARTER","CANCELED",Instant.now().toEpochMilli(),0,0,"Contract ended","cancel-1",0);service.change(request,"admin");verify(entitlementService).applyPlan(eq(tenant.getId()),eq(Set.of()),contains("Contract ended"),eq("admin"));}
@Test void planDefinitionMustIncludeFeatureDependencies(){var request=new SubscriptionApi.PlanUpsertRequest("خطة","Plan",Set.of("manufacturing.enabled"),Map.of("users",1),true,0);assertThatThrownBy(()->service.savePlan("BROKEN",request,"admin")).isInstanceOfSatisfying(BusinessRuleException.class,e->assertThat(e.getCode()).isEqualTo("ENTITLEMENT_DEPENDENCY_MISSING"));verifyNoInteractions(planRepository);}
@Test void userLimitIsEnforcedButZeroMeansUnlimited(){var limited=new SubscriptionPlan("STARTER","البداية","Starter","[\"finance.enabled\"]","{\"users\":2}");var current=new TenantSubscription("STARTER","ACTIVE",Instant.now(),null,null,"op","admin");when(subscriptionRepository.findFirstBy()).thenReturn(Optional.of(current));when(planRepository.findById("STARTER")).thenReturn(Optional.of(limited));var limits=new SubscriptionLimitService(subscriptionRepository,planRepository,new ObjectMapper());assertThatThrownBy(()->limits.assertCanAddUser(2)).isInstanceOfSatisfying(BusinessRuleException.class,e->assertThat(e.getCode()).isEqualTo("SUBSCRIPTION_USER_LIMIT_REACHED"));limited.update("البداية","Starter","[\"finance.enabled\"]","{\"users\":0}",true);assertThatCode(()->limits.assertCanAddUser(200)).doesNotThrowAnyException();}
@Test void endpointsRequireSuperAdminExplicitly(){assertThat(SubscriptionController.class.getAnnotation(PreAuthorize.class).value()).isEqualTo("hasRole('SUPER_ADMIN')");}
}
