import{ChangeDetectionStrategy,Component,inject,signal}from'@angular/core';import{HttpClient}from'@angular/common/http';import{FormsModule}from'@angular/forms';import{firstValueFrom}from'rxjs';import{I18nService}from'../../core/i18n.service';import{NotificationService}from'../../core/notification.service';import{apiErrorMessage}from'../../core/api-error';
interface Step{id:string;key:string;sequence:number;prerequisiteKey?:string;optional:boolean;status:string;version:number}interface Pack{code:string;nameKey:string;descriptionKey:string;availableVersion:number;installedVersion?:number;upgradeAvailable:boolean;status:string;requiredFeatures:string[];defaultRoles:string[];kpis:string[];importTemplates:string[];settingsJson?:string;customized:boolean;goLiveReady:boolean;version:number;steps:Step[]}
@Component({selector:'app-industry-pack-settings',imports:[FormsModule],templateUrl:'./industry-pack-settings.component.html',styleUrl:'./industry-pack-settings.component.scss',changeDetection:ChangeDetectionStrategy.OnPush})
export class IndustryPackSettingsComponent{private http=inject(HttpClient);readonly i18n=inject(I18nService);private notification=inject(NotificationService);readonly packs=signal<Pack[]>([]);readonly loading=signal(true);readonly saving=signal(false);readonly error=signal<string|null>(null);readonly settings=signal<Record<string,string>>({});constructor(){void this.load();}async load(){this.loading.set(true);try{const packs=await firstValueFrom(this.http.get<Pack[]>('/api/v1/platform/industry-packs'));this.packs.set(packs);this.settings.set(Object.fromEntries(packs.map(p=>[p.code,p.settingsJson??''])));}catch(e){this.error.set(apiErrorMessage(e,this.i18n));}finally{this.loading.set(false);}}setSettings(code:string,value:string){this.settings.update(s=>({...s,[code]:value}));}
async install(pack:Pack){if(this.saving())return;this.saving.set(true);try{await firstValueFrom(this.http.post(`/api/v1/platform/industry-packs/${pack.code}/install`,{operationId:crypto.randomUUID()}));this.notification.success(this.i18n.t('industryPack.installSuccess'));await this.load();}catch(e){this.error.set(apiErrorMessage(e,this.i18n));}finally{this.saving.set(false);}}
async upgrade(pack:Pack){if(this.saving())return;this.saving.set(true);try{await firstValueFrom(this.http.post(`/api/v1/platform/industry-packs/${pack.code}/upgrade`,{operationId:crypto.randomUUID(),expectedVersion:pack.version}));this.notification.success(this.i18n.t('industryPack.upgradeSuccess'));await this.load();}catch(e){this.error.set(apiErrorMessage(e,this.i18n));}finally{this.saving.set(false);}}
async complete(pack:Pack,step:Step,skip=false){if(this.saving())return;this.saving.set(true);try{await firstValueFrom(this.http.post(`/api/v1/platform/industry-packs/${pack.code}/steps/${encodeURIComponent(step.key)}`,{skip,expectedVersion:step.version}));await this.load();}catch(e){this.error.set(apiErrorMessage(e,this.i18n));}finally{this.saving.set(false);}}
async saveSettings(pack:Pack){if(this.saving())return;this.saving.set(true);try{await firstValueFrom(this.http.put(`/api/v1/platform/industry-packs/${pack.code}/settings`,{settingsJson:this.settings()[pack.code],expectedVersion:pack.version}));this.notification.success(this.i18n.t('industryPack.settingsSaved'));await this.load();}catch(e){this.error.set(apiErrorMessage(e,this.i18n));}finally{this.saving.set(false);}}
}
