import{ChangeDetectionStrategy,Component,inject,signal}from'@angular/core';import{HttpClient}from'@angular/common/http';import{FormsModule}from'@angular/forms';import{firstValueFrom,forkJoin}from'rxjs';import{I18nService}from'../../core/i18n.service';import{NotificationService}from'../../core/notification.service';import{apiErrorMessage}from'../../core/api-error';import{entitlementFeatureLabel}from'./entitlement-feature-label';
interface Plan{code:string;nameAr:string;nameEn:string;features:string[];limits:Record<string,number>;active:boolean;version:number}interface Subscription{planCode:string;status:string;startsAt:number;renewsAt:number;endsAt:number;version:number;updatedBy:string;updatedAt:number}interface Usage{planCode:string|null;limits:Record<string,number>;usage:Record<string,number>}interface History{fromPlan:string|null;toPlan:string;fromStatus:string|null;toStatus:string;reason:string;operationId:string;actor:string;changedAt:number}
@Component({selector:'app-subscription-settings',imports:[FormsModule],templateUrl:'./subscription-settings.component.html',styleUrl:'./subscription-settings.component.scss',changeDetection:ChangeDetectionStrategy.OnPush})export class SubscriptionSettingsComponent{private readonly http=inject(HttpClient);readonly i18n=inject(I18nService);private readonly notifications=inject(NotificationService);readonly plans=signal<Plan[]>([]);readonly current=signal<Subscription|null>(null);readonly usage=signal<Usage|null>(null);readonly history=signal<History[]>([]);readonly loading=signal(true);readonly saving=signal(false);readonly error=signal<string|null>(null);selectedCode='STARTER';status='ACTIVE';startsAt=this.dateInput(Date.now());renewsAt='';endsAt='';reason='';editCode='';editNameAr='';editNameEn='';editActive=true;editUserLimit=0;editFeatures=new Set<string>();constructor(){void this.load();}
 async load(){this.loading.set(true);this.error.set(null);try{const result=await firstValueFrom(forkJoin({plans:this.http.get<Plan[]>('/api/v1/platform/subscription/plans'),current:this.http.get<Subscription|null>('/api/v1/platform/subscription'),usage:this.http.get<Usage>('/api/v1/platform/subscription/usage'),history:this.http.get<History[]>('/api/v1/platform/subscription/history')}));this.plans.set(result.plans);this.current.set(result.current);this.usage.set(result.usage);this.history.set(result.history);if(result.current){this.selectedCode=result.current.planCode;this.status=result.current.status;this.startsAt=this.dateInput(result.current.startsAt);this.renewsAt=this.dateInput(result.current.renewsAt);this.endsAt=this.dateInput(result.current.endsAt);}this.selectPlan(result.plans.find(plan=>plan.code===this.selectedCode)??result.plans[0]);}catch(e){this.error.set(apiErrorMessage(e,this.i18n));}finally{this.loading.set(false);}}
 async change(){if(this.saving()||!this.reason.trim())return;this.saving.set(true);this.error.set(null);try{const current=this.current();await firstValueFrom(this.http.post('/api/v1/platform/subscription/change',{planCode:this.selectedCode,status:this.status,startsAt:this.epoch(this.startsAt),renewsAt:this.epoch(this.renewsAt),endsAt:this.epoch(this.endsAt),reason:this.reason.trim(),operationId:crypto.randomUUID(),expectedVersion:current?.version??0}));this.reason='';this.notifications.success(this.i18n.t('subscription.saved'));await this.load();}catch(e){this.error.set(apiErrorMessage(e,this.i18n));}finally{this.saving.set(false);}}
 selectPlan(plan?:Plan){if(!plan)return;this.editCode=plan.code;this.editNameAr=plan.nameAr;this.editNameEn=plan.nameEn;this.editActive=plan.active;this.editUserLimit=plan.limits['users']??0;this.editFeatures=new Set(plan.features);}selectPlanByCode(code:string){this.selectPlan(this.plans().find(plan=>plan.code===code));}
 toggleFeature(key:string,enabled:boolean){const next=new Set(this.editFeatures);enabled?next.add(key):next.delete(key);this.editFeatures=next;}
 async savePlan(){const plan=this.plans().find(p=>p.code===this.editCode);if(!plan||this.saving())return;this.saving.set(true);this.error.set(null);try{await firstValueFrom(this.http.put(`/api/v1/platform/subscription/plans/${plan.code}`,{nameAr:this.editNameAr,nameEn:this.editNameEn,featureKeys:[...this.editFeatures],limits:{users:this.editUserLimit},active:this.editActive,expectedVersion:plan.version}));this.notifications.success(this.i18n.t('subscription.planSaved'));await this.load();}catch(e){this.error.set(apiErrorMessage(e,this.i18n));}finally{this.saving.set(false);}}
  allFeatures(){return[...new Set(this.plans().flatMap(p=>p.features))].sort();}featureLabel(key:string){return entitlementFeatureLabel(this.i18n,key);}format(value:number){return value?new Intl.DateTimeFormat(undefined,{dateStyle:'medium'}).format(value):'—';}private dateInput(value:number){return value?new Date(value).toISOString().slice(0,10):'';}private epoch(value:string){return value?new Date(`${value}T00:00:00Z`).getTime():0;}

  // BORTQALA_FEEDBACK_20260816_PLAN_LABELS
  planLabel(code: string | null | undefined): string {
    const t = (k: string, fb?: string) => this.i18n.t(k, undefined, fb);
    if (!code) return t('subscription.noPlan');
    const labels: Record<string, string> = {
      ENTERPRISE: 'subscription.planEnterprise',
      GROWTH: 'subscription.planGrowth',
      STARTER: 'subscription.planStarter',
    };
    const key = labels[code.toUpperCase()];
    return key ? t(key, code) : code;
  }
}
