package com.bemo.hr.product.onboarding;
import com.bemo.hr.attendance.infrastructure.ImportBatchRepository;import com.bemo.hr.audit.application.AuditService;import com.bemo.hr.employee.infrastructure.AttendanceCategoryRepository;import com.bemo.hr.product.pack.*;import com.bemo.hr.shared.domain.BusinessRuleException;import com.bemo.hr.workforce.*;import lombok.RequiredArgsConstructor;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import tools.jackson.databind.ObjectMapper;import java.util.*;
@Service @RequiredArgsConstructor
public class GuidedOnboardingService{
private final IndustryPackRepository packRepository;private final TenantIndustryPackRepository tenantPackRepository;private final IndustryOnboardingStepRepository stepRepository;private final OnboardingAssessmentRepository assessmentRepository;private final ContractorRepository contractorRepository;private final AttendanceCategoryRepository categoryRepository;private final WorkerRepository workerRepository;private final WorkforceImportBatchRepository workforceImportRepository;private final ImportBatchRepository attendanceImportRepository;private final WorkforceAdvanceRepository advanceRepository;private final ContractorSettlementRepository settlementRepository;private final ObjectMapper objectMapper;private final AuditService auditService;
@Transactional(readOnly=true)public GuidedOnboardingApi.OverviewResponse overview(String code){var context=context(code,false);return calculate(code,context.pack(),context.steps(),0);}
@Transactional public GuidedOnboardingApi.OverviewResponse assess(String code,GuidedOnboardingApi.AssessRequest request,String actor){var context=context(code,true);var replay=assessmentRepository.findByTenantPackIdAndOperationId(context.pack().getId(),request.operationId());if(replay.isPresent())return fromSnapshot(code,replay.get(),context.steps());autoComplete(context.steps(),actor);var result=calculate(code,context.pack(),context.steps(),System.currentTimeMillis());String issues;try{issues=objectMapper.writeValueAsString(result.issues());}catch(Exception ex){throw error("ONBOARDING_ASSESSMENT_INVALID",HttpStatus.INTERNAL_SERVER_ERROR);}var saved=assessmentRepository.save(new OnboardingAssessment(context.pack().getId(),request.operationId(),result.setupProgress(),result.dataQualityScore(),result.readiness(),issues,actor));auditService.record("ASSESS","ONBOARDING",saved.getId(),actor,"{\"pack\":\""+code+"\",\"progress\":"+result.setupProgress()+",\"quality\":"+result.dataQualityScore()+",\"readiness\":\""+result.readiness()+"\"}",null);return new GuidedOnboardingApi.OverviewResponse(result.packCode(),result.setupProgress(),result.dataQualityScore(),result.readiness(),saved.getAssessedAt().toEpochMilli(),result.issues(),result.steps());}
private void autoComplete(List<IndustryOnboardingStep> steps,String actor){Map<String,IndustryOnboardingStep> byKey=new HashMap<>();for(var step:steps){byKey.put(step.getStepKey(),step);if(step.getStatus()==IndustryOnboardingStep.Status.BLOCKED&&terminal(byKey.get(step.getPrerequisiteKey())))step.ready();if(step.getStatus()==IndustryOnboardingStep.Status.READY&&satisfied(step.getStepKey()))step.complete(actor,false);stepRepository.save(step);}}
private boolean terminal(IndustryOnboardingStep step){return step!=null&&(step.getStatus()==IndustryOnboardingStep.Status.COMPLETED||step.getStatus()==IndustryOnboardingStep.Status.SKIPPED);}
private boolean satisfied(String key){return switch(key){case"industryPack.step.company"->true;case"industryPack.step.contractors"->contractorRepository.count()>0;case"industryPack.step.categories"->categoryRepository.count()>0;case"industryPack.step.workers"->workerRepository.count()>0;case"industryPack.step.attendance"->workforceImportRepository.existsByStatus("IMPORTED")||attendanceImportRepository.count()>0;case"industryPack.step.advances"->advanceRepository.count()>0;case"industryPack.step.settlement"->settlementRepository.count()>0;default->false;};}
private GuidedOnboardingApi.OverviewResponse calculate(String code,TenantIndustryPack pack,List<IndustryOnboardingStep> steps,long assessedAt){List<GuidedOnboardingApi.IssueResponse> issues=new ArrayList<>();check(issues,"CONTRACTORS","onboarding.issue.contractors","/workforce/contractors",contractorRepository.count(),true);check(issues,"CATEGORIES","onboarding.issue.categories","/categories",categoryRepository.count(),true);check(issues,"WORKERS","onboarding.issue.workers","/workforce/workers",workerRepository.count(),true);long imports=workforceImportRepository.existsByStatus("IMPORTED")||attendanceImportRepository.count()>0?1:0;check(issues,"IMPORT","onboarding.issue.import","/imports",imports,true);check(issues,"SETTLEMENT","onboarding.issue.settlement","/workforce/settlement-periods",settlementRepository.count(),true);int passed=5-issues.size();int quality=passed*100/5;long required=steps.stream().filter(s->!s.isOptional()).count();long complete=steps.stream().filter(s->!s.isOptional()&&s.getStatus()==IndustryOnboardingStep.Status.COMPLETED).count();int progress=required==0?0:(int)(complete*100/required);String readiness=progress==100&&quality>=80?"READY":issues.stream().anyMatch(GuidedOnboardingApi.IssueResponse::blocker)?"BLOCKED":"IN_PROGRESS";return new GuidedOnboardingApi.OverviewResponse(code,progress,quality,readiness,assessedAt,List.copyOf(issues),stepViews(steps));}
private void check(List<GuidedOnboardingApi.IssueResponse> issues,String code,String key,String route,long count,boolean blocker){if(count==0)issues.add(new GuidedOnboardingApi.IssueResponse(code,key,route,count,blocker));}
private List<GuidedOnboardingApi.StepResponse> stepViews(List<IndustryOnboardingStep> steps){return steps.stream().map(s->new GuidedOnboardingApi.StepResponse(s.getStepKey(),s.getSequenceNo(),s.isOptional(),s.getStatus().name())).toList();}
private GuidedOnboardingApi.OverviewResponse fromSnapshot(String code,OnboardingAssessment snapshot,List<IndustryOnboardingStep> steps){try{var issues=List.of(objectMapper.readValue(snapshot.getIssuesJson(),GuidedOnboardingApi.IssueResponse[].class));return new GuidedOnboardingApi.OverviewResponse(code,snapshot.getSetupProgress(),snapshot.getDataQualityScore(),snapshot.getReadiness(),snapshot.getAssessedAt().toEpochMilli(),issues,stepViews(steps));}catch(Exception ex){throw error("ONBOARDING_ASSESSMENT_INVALID",HttpStatus.INTERNAL_SERVER_ERROR);}}
private Context context(String code,boolean lock){IndustryPack definition=packRepository.findByCodeAndStatus(code,"ACTIVE").orElseThrow(()->error("INDUSTRY_PACK_NOT_FOUND",HttpStatus.NOT_FOUND));TenantIndustryPack pack=(lock?tenantPackRepository.findByPackIdForUpdate(definition.getId()):tenantPackRepository.findByPackId(definition.getId())).orElseThrow(()->error("INDUSTRY_PACK_NOT_INSTALLED",HttpStatus.CONFLICT));return new Context(pack,stepRepository.findByTenantPackIdOrderBySequenceNo(pack.getId()));}private record Context(TenantIndustryPack pack,List<IndustryOnboardingStep>steps){}private static BusinessRuleException error(String code,HttpStatus status){return new BusinessRuleException(code,code,status);}}
